import { LeadCMDesignSettingsInterface } from './WidgetSettingsTypes';
import { currentVersion } from './Versions';
import {
    BackgroundType,
    ButtonBorderAnimationType,
    ButtonType,
    DesktopButtonPosition,
    DesktopTooltipPosition,
    FontWeight,
    MobileButtonPosition,
    MobilePositionTextInOpenButton,
    MobileTooltipPosition,
    MobileType,
    TemplateType,
    TooltipPosition,
    TooltipType,
} from './WidgetSettingsEnums';

// this data is default for a new widget
// noinspection JSUnusedGlobalSymbols
export const LeadCMSettingsDefaultData: LeadCMDesignSettingsInterface = {
    url: 'https://icallback.convolo.ai/api/v1/add_call/',

    version: currentVersion,

    poweredUrl: `https://convolo.ai`,
    formItems: [
        {
            title: '1st step',
            okText: 'Next',
            name: 'Your Work Email Here',
            type: 'text',
        },
        {
            title: '2nd step',
            okText: 'Next',
            name: 'Your Work Email Here',
            type: 'text',
        },
        {
            title: '3rd step',
            okText: 'Next',
            name: 'Your Work Email Here',
            type: 'text',
        },
        {
            title: '4th step',
            okText: 'Finish',
            name: 'Your Work Email Here',
            type: 'text',
        },
    ],
    staticUrl: 'https://testpage.convolo.ai/',
    isActive: false,
    nonWorkingTime: false,
    onDemand: false,
    spaEnabled: false,
    spaFullTime: false,
    secondsToGo: 55,
    widgetTexts: {
        chooseTimeButton: 'Välj vilken tid du vill bli uppringd.',
        tipText: 'Nyfiken? Klicka här för att bli uppringd inom 55 sekunder!',
        nonWorkingTipText: 'Nyfiken? Klicka här för att bli uppringd!',
        userName: 'Manager',
        userPosition: 'SÄLJCHEF',
        title: 'Bli uppringd 📞',
        subTitle: 'Välj dag och tid nedan',
        text: '',
        departmentSelectorFirstLine: '',
        departmentSelectorSecondLine: '',
        timeSelectorFirstLine: '',
        timeSelectorSecondLine: '',
        nonWorkingTitle: 'Bli uppringd inom 55 sekunder 📞',
        nonWorkingSubTitle: 'Så hjälper vi dig på bästa sätt!',
        nonWorkingText: 'Så ringer vi dig, när vi är tillbaka.',
        afterOrderingTitle: 'Tack för att du beställde ett samtal',
        afterOrderingText: 'Vi kopplar nu ditt samtal',
        managerTryingToReachYou: '%MANAGER% försöker just nu nå dig!!',
        enterYourPhone: 'Skriv in ditt nummer',
        callingTo: 'Vi ringer dig nu på %PHONE%:',
        pleasePickUp: 'Vänligen svara på din telefon',
        successfullyReached: 'Kul att få kontakt. Ha en riktigt bra dag!',
        rateAgent: 'Rate your call with',
        fillFormBelowTitle: 'Fill in the form below',
        fillFormBelowSubTitle: 'to help us serve you better',
        cantReach:
            'Vi kunde tyvärr inte nå dig. Vänligen kontrollera att du skrev rätt telefonnummer. ',
        defaultMessage:
            'Tack för din förfrågan! Vi hinner tyvärr inte ' +
            'kontakta dig inom utsatt tid, men hör av oss så fort vi kan. ',
        callMe: 'Ring mig!',
        callIsFree: 'samtalet är gratis',
        closeWindow: 'Stäng',
        chooseDepartment: 'Välj vilken avdelning du vill få kontakt med:',
        numberWrong: 'Felaktigt nummer! ',
        countryWrong: 'Detta land stöds inte! ',
        weCallYouLater: 'Tack! Vi kommer att ringa dig när vi är inne på kontoret igen.',
        chooseTimeYouWillBeCalled: 'Välj vilken tid du vill bli uppringd:',
        weCallYouLaterIn: 'Tack! Vi kommer att ringa dig på %DATE% i %TIME%!',
        gdprBeforeLinkText: 'Jag godkänner',
        gdprLinkText: 'integritetspolicy och användarvillkor',
        selectDepartmentButton: 'Välj',
        phoneNumberExample: '',
        ratingTextAreaPlaceholderText: 'Tell us on how can we improve',
        ratingDescription: 'Rate your experience',
        ratingCloseWindowButton: 'Submit',
        press: 'press',
        enter: 'Enter',
        mobileTipText: 'Test mobile text',
    },
    widgetStyles: {
        modalOpacity: '1',
        avatarUrl: ``,
        avatarBlockHeight: '80px',
        avatarWidth: '80px',
        avatarMobileWidth: '80px',
        avatarBorderRadius: '0%',

        // leadconnect white logo
        logoUrl: '',
        logoWidth: '200px',
        logoHeight: 'auto',
        logoBottomGap: '12px',

        template: TemplateType.LEADCM_DEFAULT,
        backgroundType: BackgroundType.DARK,

        headerHeightDefaultTemplate: '230px',
        headerBgColor: '#213A52',
        headerBgShadow: 'rgba(0, 0, 0, 0.0)',
        headerPrimaryColor: '#FFFFFF',
        headerSecondaryColor: '#B4D7F9',
        primaryTextColor: '#213A52',
        secondaryTextColor: '#222222',
        primaryColor: '#1785EB',
        defaultActiveColor: '#EF5777',

        activeColor: '#eb1a2c', // hex
        baseFontFamily:
            '"Roboto", -apple-system, "Oxygen", "Ubuntu", "Cantarell", ' +
            '"Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        titleFontFamily: 'inherit',
        subTitleFontFamily: 'inherit',
        baseFontSize: '16px',
        baseColor: '#485460',
        secondaryColorHue: 208, // Just hue value in hsl scheme
        borderRadius: '3px',

        imageBg: '',
        imageBgHeight: '336px',
        modalBorderRadius: '6px',
        sectionBorderRadius: '4px',
        elementBorderRadius: '4px',
        titleMarginBottom: '29px',
        titleFontSize: '24px',
        titleLineHeight: '28px',
        titleFontWeight: FontWeight.BOLD,
        subTitleFontSize: '18px',
        subTitleFontWeight: FontWeight.NORMAL,
        subTitleLineHeight: '1.2em',
        subtitleAccentColor: '#fff',
        selectTimeLinkColor: 'rgba(101, 119, 128, 0.7)',
        powerByColor: '#222',
        poweredIsShow: true,
        poweredByText: 'powered by',
        poweredUnderlineIsShow: true,
        poweredUnderlineColor: '#1c6bc9',
        poweredSvgFill: '#AAAAAA',
        poweredSvgHeight: '13px',
        poweredSvgWidth: '67px',
        customPoweredIcon: undefined,
        sectionBgColor: '#fff',

        imageBgWaveOn: true,

        // Config for leadback modal
        modalBgColor: 'rgba(255, 255, 255, .83)',
        modalMinHeight: ' 456px',
        backdropBgColor: 'rgba(0, 0, 0, 0.33)',
        backdropImage: 'https://images.pexels.com/photos/1122408/pexels-photo-1122408.jpeg',
        bannerImage: 'https://images.pexels.com/photos/1981945/pexels-photo-1981945.jpeg',

        allowChoosingTime: true,
        chooseTimeOnlyNonWorkingTime: false,
        openTimeSelectorForNonworkingTimeByDefault: true,
        showAfterMS: 45000,
        cooldownWhenLeavingMS: 30000,

        useTimer: true,
        useTimerMilliseconds: true,

        useGDPR: false,
        gdprLink: '#',
        departmentsDropdownSelector: false,

        showAvatarInModal: false,
        showAvatarInNonworkingTime: true,

        onlyCountries: '',
        departmentsSelectorBeforePhoneField: false,
        isSetRating: false,
        isSetRatingUnreachable: true,
        ratingTagButtonBorderRadius: '8px',
        ratingTagButtonColor: '#797979',
        ratingActiveTagButtonColor: '#0074FF',
        ratingTagButtonBackgroundColor: '#7979791A',
        ratingActiveTagButtonBackgroundColor: '#0074FF1A',
        ratingTextAreaPlaceholderColor: '#858585',
        ratingTagsHeight: '400px',
        disableExternalCss: false,
        isSendLeadForm: false,
        leadFormInputBackground: '#fff',
        leadFormInputColor: '#0074FF',
        leadFormEnterTextVisible: true,
        leadFormModalBackground: '#0074FF',
        leadFormModalBorderRadius: '16px',
        leadFormElementBorderRadius: '8px',
        leadFormTextColor: '#fff',
        leadFormButtonBackground: '#fff',
        leadFormButtonColor: '#0074FF',
        leadFormButtonActiveColor: '#0074FF',
        leadFormButtonActiveBackground: '#edededfb',
        leadFormButtonDisActiveBackground: '#57A4FF',
        leadFormInputColorPlaceholderColor: '#858585',
        mobileStyles: MobileType.DEFAULT,
        mobileUseMobileStyles: false,
        mobilePositionTextInOpenButton: MobilePositionTextInOpenButton.RIGHT,
        mobileFullTooltipAfterHide: true,
        mobileFullTooltipBeforeHide: true,
        mobileWidgetButtonStylesWidth: '65px',
        mobileWidgetButtonStylesHeight: '65px',
        mobileWidgetButtonStylesZIndex: '99999',
        mobileUseMobileAnimationTextButtonShow: true,
        mobileFillBottomCornerRadius: '8px',
        mobileFillBottomBackgroundColor: '#57A4FF',
        mobileHeightContainer: '150px',
        mobileFillBottomCloseButtonColor: '#A0A0A0',
        mobileFillBottomCloseButtonFontSize: '30px',
        mobilButtonBorderRadius: '16px',
        mobileButtonOpenTextWidth: '300px',
        mobileButtonBackgroundIconContainer: '#57A4FF',
        mobileWidgetTooltipCloseFontSize: '30px',
        mobileTooltipSideSize: '100px',
        mobileTooltipSideWidth: '40vw',
    },
    buttonStyles: {
        buttonTemplate: ButtonType.LEADCM,

        buttonPositionTop: 'auto',
        buttonPositionRight: '50px',
        buttonPositionBottom: '50px',
        buttonPositionLeft: 'auto',

        buttonCustomImage: '',

        buttonColor: '#fff',
        buttonPulseColor: '#0c72f3',
        buttonBgColor: '#2196F3',

        buttonBorderRadius: '4px',
        buttonBorderAnimation: ButtonBorderAnimationType.PULSE,
        buttonColorShiftAnimation: false,
        buttonSize: '70px',
        buttonIcon: 4, // range 1...4
        mobileButtonPosition: MobileButtonPosition.RIGHT,
        desktopButtonPosition: DesktopButtonPosition.BOTTOM_RIGHT,
        mobileButtonPositionX: '10px',
        mobileButtonPositionY: '10px',
        desktopButtonPositionX: '10px',
        desktopButtonPositionY: '10px',
    },
    departments: [],
    ratingTitles: [
        {
            level: 1,
            tags: ['very bad'],
        },
        {
            level: 2,
            tags: ['bad'],
        },
        {
            level: 3,
            tags: ['normal'],
        },
        {
            level: 4,
            tags: ['good'],
        },
        {
            level: 5,
            tags: ['excellent'],
        },
    ],
    defaultDepartmentId: 'sales',
    timeoutDepartmentKey: undefined,
    timeoutDepartmentTimeoutMs: undefined,
    tooltipStyles: {
        tooltipType: TooltipType.BORDERED,
        tooltipPosition: TooltipPosition.LEFT,
        mobileTooltipPosition: MobileTooltipPosition.LEFT,
        desktopTooltipPosition: DesktopTooltipPosition.LEFT,
        tooltipWidth: '280px',
        tooltipBg: '0, 0%, 0%', // hsl
        tooltipColor: '#FFF',

        defaultTooltipBg: '#FFF',
        defaultTooltipColor: '#000',
        tooltipBorderColor: '#2196F3',
        tooltipBorderRadius: '10px',
        tooltipCloseColor: '#8c8c8c',
        showTooltipAfterMs: 20000,
        showAvatarInTooltip: false,
        showPhoneField: false,
        blockPopupIfShowPhoneField: false,
        checkPhoneNumber: false,
    },
    country: 'SE',
    phoneNumberWithoutDialCode: false,
    phoneNumberWithLocalCodePlaceholder: false,
    ip: '',
    occ_phone: null,
    occ_api: null,
    occ_api_nobutton: null,
    alreadyShownPopup: false,
    alreadyShownTooltip: false,
};

//
// function getTestUserName() {
//     const names = [
//         'Peter Stenmark',
//         'Liam Öberg',
//         'Maximilian Adelsköld',
//         'Anders Hansdotter',
//         'Gorm Skoglund',
//         'Ivar Lagerquist',
//         'Wilhelm Strömberg',
//         'Eric Almgren',
//         'Vincent Westermark',
//         'Jan Bergh',
//         'Sverker Ohlson',
//     ];
//     return names[randomInteger(0, names.length - 1)];
// }
