import { currentVersion } from '@shared/convolo-icallback-js/types/callback_widget_schemas/Versions';
import {
    BackgroundType,
    ButtonBorderAnimationType,
    ButtonType,
    DesktopButtonPosition,
    DesktopTooltipPosition,
    FontWeight,
    MobileButtonPosition,
    MobilePositionTextInOpenButton,
    MobileTooltipPosition,
    MobileType,
    TemplateType,
    TooltipPosition,
    TooltipType,
} from '@shared/convolo-icallback-js/types/callback_widget_schemas/WidgetSettingsEnums';
import { LeadCMDesignSettingsInterface } from '@shared/convolo-icallback-js/types/callback_widget_schemas/WidgetSettingsTypes';
import { randomInteger } from '@shared/convolo-core/helpers/helpers/random-integer';

export const LeadCMSettingsTestData: LeadCMDesignSettingsInterface = {
    url: 'https://icallback.leadcm.com/api/v1/add_call/',

    version: currentVersion,

    poweredUrl: `https://convolo.ai`,
    formItems: [
        {
            title: '1st step',
            okText: 'Next',
            name: 'Your Work Email Here',
            type: 'text',
        },
        {
            title: '2nd step',
            okText: 'Next',
            name: 'Your Work Email Here',
            type: 'text',
        },
        {
            title: '3rd step',
            okText: 'Next',
            name: 'Your Work Email Here',
            type: 'text',
        },
        {
            title: '4th step',
            okText: 'Finish',
            name: 'Your Work Email Here',
            type: 'text',
        },
    ],
    staticUrl: 'https://testpage.leadcm.com/',
    isActive: false,
    nonWorkingTime: false,
    onDemand: false,
    secondsToGo: 135,
    spaEnabled: false,
    widgetTexts: {
        nonWorkingTitle: 'Bli uppringd inom 55 sekunder 📞',
        nonWorkingSubTitle: 'Så hjälper vi dig på bästa sätt!',
        nonWorkingText: 'Så ringer vi dig, när vi är tillbaka.',
        chooseTimeButton: 'Välj vilken tid du vill bli uppringd.',
        tipText: 'Nyfiken? Klicka här för att bli uppringd inom 55 sekunder!',
        nonWorkingTipText: 'Nyfiken? Klicka här för att bli uppringd!',
        selectDepartmentButton: 'Välj',

        userName: getTestUserName(),
        userPosition: 'SÄLJCHEF',
        title: 'Bli uppringd 📞',
        subTitle: 'Välj dag och tid nedan',
        text: '',
        departmentSelectorFirstLine: 'dep first line!',
        departmentSelectorSecondLine: 'dep second line!',
        timeSelectorFirstLine: 'time first line!',
        timeSelectorSecondLine: 'time second line!',
        afterOrderingTitle: 'Tack för att du beställde ett samtal',
        afterOrderingText: 'Vi kopplar nu ditt samtal',
        managerTryingToReachYou: '%MANAGER% försöker just nu nå dig!!',
        enterYourPhone: 'Skriv in ditt nummer',
        callingTo: 'Vi ringer dig nu på %PHONE%:',
        pleasePickUp: 'Vänligen svara på din telefon',
        successfullyReached: 'Kul att få kontakt. Ha en riktigt bra dag!',
        rateAgent: 'Rate your call with',
        fillFormBelowTitle: 'Fill in the form below',
        fillFormBelowSubTitle: 'to help us serve you better',
        cantReach:
            'Vi kunde tyvärr inte nå dig. Vänligen kontrollera att du skrev rätt telefonnummer. ',
        defaultMessage:
            'Tack för din förfrågan! Vi hinner tyvärr inte ' +
            'kontakta dig inom utsatt tid, men hör av oss så fort vi kan. ',
        callMe: 'Ring mig!',
        callIsFree: 'samtalet är gratis',
        closeWindow: 'Stäng',
        chooseDepartment: 'Välj vilken avdelning du vill få kontakt med:',
        numberWrong: 'Felaktigt nummer! ',
        countryWrong: 'Detta land stöds inte! ',
        weCallYouLater: 'Tack! Vi kommer att ringa dig när vi är inne på kontoret igen.',
        chooseTimeYouWillBeCalled: 'Välj vilken tid du vill bli uppringd:',
        weCallYouLaterIn: 'Tack! Vi kommer att ringa dig på %DATE% i %TIME%!',
        gdprBeforeLinkText: 'Jag godkänner',
        gdprLinkText: 'integritetspolicy och användarvillkor',
        phoneNumberExample: 'Ex. +46 8 1234567',
        ratingTextAreaPlaceholderText: 'Tell us on how can we improve...',
        ratingDescription: 'Rate your experience',
        ratingCloseWindowButton: 'Submit',
        press: 'press',
        enter: 'Enter',
        mobileTipText: 'Test mobile text',
    },
    widgetStyles: {
        modalOpacity: '1',
        avatarUrl: `https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60`,
        //   avatarUrl: ``,
        avatarBlockHeight: '80px',
        avatarWidth: '100%',
        avatarMobileWidth: '80px',
        avatarBorderRadius: '0',

        logoUrl: 'https://www.leadconnect.se/assets/images/leadconnect-logo-black-small-280x97.png',
        logoWidth: '175px',
        logoHeight: '60px',
        logoBottomGap: '12px',

        template: TemplateType.LEADCM_DEFAULT,
        backgroundType: BackgroundType.NONE,

        activeColor: '#eb1a2c', // hex

        headerHeightDefaultTemplate: '168px',
        headerBgColor: '#f2f2f2',
        headerBgShadow: 'rgba(0, 0, 0, 0)',
        headerPrimaryColor: '#444',
        headerSecondaryColor: '#777',
        subtitleAccentColor: '#FFFFFF',
        primaryTextColor: '#404040',
        secondaryTextColor: '#222222',
        primaryColor: '#38373c',
        defaultActiveColor: '#abbde0',
        imageBg: '',
        imageBgHeight: '336px',
        imageBgWaveOn: true,

        baseFontFamily: 'Classico, Arial, Verdana, Helvetica, sans-serif',
        titleFontFamily: 'inherit',
        subTitleFontFamily: 'inherit',
        baseFontSize: '16px',
        baseColor: '#404040',
        secondaryColorHue: 208, // Just hue value in hsl scheme
        borderRadius: '3px',

        modalBorderRadius: '0',
        sectionBorderRadius: '0',
        elementBorderRadius: '3px',
        titleMarginBottom: '29px',
        titleFontSize: '24px',
        titleLineHeight: '28px',
        titleFontWeight: FontWeight.BOLD,
        subTitleFontSize: '18px',
        subTitleFontWeight: FontWeight.NORMAL,
        subTitleLineHeight: '1.2em',
        selectTimeLinkColor: 'rgba(0, 0, 0, 0.7)',
        powerByColor: '#000',
        poweredIsShow: true,
        poweredByText: 'powered by',
        poweredUnderlineIsShow: true,
        poweredUnderlineColor: '#1c6bc9',
        poweredSvgFill: '#AAAAAA',
        poweredSvgHeight: '13px',
        poweredSvgWidth: '67px',
        customPoweredIcon: undefined,
        sectionBgColor: '#fff',

        // Config for leadback modal
        modalBgColor: 'rgba(255, 255, 255, .83)',
        modalMinHeight: ' 456px',
        backdropBgColor: 'rgba(0, 0, 0, 0.33)',
        backdropImage: 'https://images.pexels.com/photos/1122408/pexels-photo-1122408.jpeg',
        bannerImage: 'https://images.pexels.com/photos/1981945/pexels-photo-1981945.jpeg',

        allowChoosingTime: true,
        chooseTimeOnlyNonWorkingTime: false,
        openTimeSelectorForNonworkingTimeByDefault: true,
        showAfterMS: 30000,
        cooldownWhenLeavingMS: 0,

        useTimer: true,
        useTimerMilliseconds: true,

        useGDPR: false,
        gdprLink: '#',
        departmentsDropdownSelector: false,
        departmentsSelectorBeforePhoneField: false,

        showAvatarInModal: false,
        showAvatarInNonworkingTime: true,
        onlyCountries: '',
        isSetRating: true,
        isSetRatingUnreachable: true,
        ratingTagButtonBorderRadius: '8px',
        ratingTagButtonColor: '#797979',
        ratingActiveTagButtonColor: '#0074FF',
        ratingTagButtonBackgroundColor: '#7979791A',
        ratingActiveTagButtonBackgroundColor: '#0074FF1A',
        ratingTextAreaPlaceholderColor: '#858585',
        ratingTagsHeight: '400px',
        disableExternalCss: false,
        isSendLeadForm: true,
        leadFormInputBackground: '#fff',
        leadFormInputColor: '#0074FF',
        leadFormEnterTextVisible: true,
        leadFormModalBackground: '#0074FF',
        leadFormModalBorderRadius: '16px',
        leadFormElementBorderRadius: '8px',
        leadFormTextColor: '#fff',
        leadFormButtonBackground: '#fff',
        leadFormButtonColor: '#0074FF',
        leadFormButtonActiveColor: '#0074FF',
        leadFormButtonActiveBackground: '#edededfb',
        leadFormButtonDisActiveBackground: '#57A4FF',
        leadFormInputColorPlaceholderColor: '#858585',
        mobileStyles: MobileType.DEFAULT,
        mobileUseMobileStyles: false,
        mobilePositionTextInOpenButton: MobilePositionTextInOpenButton.RIGHT,
        mobileFullTooltipAfterHide: true,
        mobileFullTooltipBeforeHide: true,
        mobileWidgetButtonStylesWidth: '65px',
        mobileWidgetButtonStylesHeight: '65px',
        mobileWidgetButtonStylesZIndex: '99999',
        mobileUseMobileAnimationTextButtonShow: true,
        mobileFillBottomCornerRadius: '8px',
        mobileFillBottomBackgroundColor: '#57A4FF',
        mobileHeightContainer: '150px',
        mobileFillBottomCloseButtonColor: '#A0A0A0',
        mobileFillBottomCloseButtonFontSize: '30px',
        mobilButtonBorderRadius: '16px',
        mobileButtonOpenTextWidth: '300px',
        mobileButtonBackgroundIconContainer: '#57A4FF',
        mobileWidgetTooltipCloseFontSize: '30px',
        mobileTooltipSideSize: '100px',
        mobileTooltipSideWidth: '40vw',
    },
    buttonStyles: {
        buttonTemplate: ButtonType.LEADCM,

        buttonPositionTop: 'auto',
        buttonPositionRight: '50px',
        buttonPositionBottom: '50px',
        buttonPositionLeft: 'auto',

        buttonCustomImage: 'https://testpage.leadcm.com/images/medlink.gif',

        buttonColor: '#fff',
        buttonPulseColor: '#0c72f3',
        buttonBgColor: '#2196F3',

        buttonBorderRadius: '4px',
        buttonBorderAnimation: ButtonBorderAnimationType.PULSE,
        buttonColorShiftAnimation: false,
        buttonSize: '70px',
        buttonIcon: 4, // range 1...4
        mobileButtonPosition: MobileButtonPosition.RIGHT,
        desktopButtonPosition: DesktopButtonPosition.BOTTOM_RIGHT,
        mobileButtonPositionX: '10px',
        mobileButtonPositionY: '10px',
        desktopButtonPositionX: '10px',
        desktopButtonPositionY: '10px',
    },
    departments: [
        { id: 'sales', name: 'Sales', key: '123' },
        { id: 'support', name: 'Support', key: '456' },
        { id: 'other', name: 'Other', key: '789' },
    ],
    ratingTitles: [
        {
            level: 1,
            tags: ['Terrible service', 'No support', 'Interrupts', 'Slow work'],
        },
        {
            level: 2,
            tags: ['Bad service', 'Many questions', 'Long answer'],
        },
        {
            level: 3,
            tags: ['Nice service', 'Medium support', 'Satisfactory answer'],
        },
        {
            level: 4,
            tags: ['Good service', 'Speed and Efficiency', 'Speed and Efficiency'],
        },
        {
            level: 5,
            tags: ['Great service', 'Interrupts', 'I will recommend'],
        },
    ],
    defaultDepartmentId: 'sales',
    timeoutDepartmentKey: '0123',
    timeoutDepartmentTimeoutMs: 5000,
    tooltipStyles: {
        tooltipType: TooltipType.BORDERED,
        tooltipPosition: TooltipPosition.LEFT,
        mobileTooltipPosition: MobileTooltipPosition.LEFT,
        desktopTooltipPosition: DesktopTooltipPosition.LEFT,
        tooltipWidth: '280px',
        tooltipBg: '0, 0%, 0%', // hsl

        defaultTooltipBg: '#FFF',
        defaultTooltipColor: '#000',
        tooltipColor: '#FFF',
        tooltipBorderColor: '#2196F3',
        tooltipBorderRadius: '10px',
        tooltipCloseColor: '#8c8c8c',
        showTooltipAfterMs: 1000,
        showAvatarInTooltip: true,
        showPhoneField: false,
        blockPopupIfShowPhoneField: false,
        checkPhoneNumber: true,
    },
    country: 'SE',
    phoneNumberWithoutDialCode: false,
    phoneNumberWithLocalCodePlaceholder: false,
    ip: '',
    occ_phone: null,
    occ_api: null,
    occ_api_nobutton: null,
    alreadyShownPopup: false,
    alreadyShownTooltip: false,
};

function getTestUserName() {
    const names = [
        'Peter',
        'Liam',
        'Maximilian',
        'Anders',
        'Gorm',
        'Ivar',
        'Wilhelm',
        'Eric',
        'Vincent',
        'Jan',
        'Sverker',
    ];
    const surnames = [
        'Stenmark',
        'Öberg',
        'Adelsköld',
        'Hansdotter',
        'Skoglund',
        'Lagerquist',
        'Strömberg',
        'Almgren',
        'Westermark',
        'Bergh',
        'Ohlson',
    ];

    return `${names[randomInteger(0, names.length - 1)]} ${
        surnames[randomInteger(0, surnames.length - 1)]
    }`;
}
